### ISSUE TITLE
Would you like to add link to tianshou's MARL doc?

### ISSUE THREAD

**Issue by Trinkle23897** [WillDudley/Tianshou-MARL-Examples#1]
as title

**Comment by WillDudley** [comment]
@Trinkle23897 Yes, that'd be great.

**Comment by WillDudley** [comment]
@Trinkle23897 I'm moving this to https://github.com/WillDudley/PettingZoo/tree/docs_API_update/tutorials/Tianshou (it will be on the PZ website), you're free to mirror and reference it.
